const SEVERITY_EMOJI = {
  CRITICAL: '🔴',
  HIGH:     '🟠',
  MEDIUM:   '🟡',
  LOW:      '🟢',
  INFO:     '⚪',
  CLEAN:    '✅',
};

const VERDICT_EMOJI = {
  CONFIRMED:  '✅ CONFIRMED',
  ADJUSTED:   '🔧 ADJUSTED',
  DOWNGRADED: '⬇️ DOWNGRADED',
  MITIGATED:  '🛡️ MITIGATED',
  REJECTED:   '❌ REJECTED',
};

export function generateReport(prData, actorReport, criticReport) {
  const { pr, stats } = prData;
  const meta = criticReport.validation_metadata;
  const riskEmoji = SEVERITY_EMOJI[meta.final_risk_level] || '⚪';

  const confirmedFindings = criticReport.validated_findings
    .filter(vf => vf.verdict !== 'REJECTED');
  const rejectedFindings = criticReport.validated_findings
    .filter(vf => vf.verdict === 'REJECTED');

  const lines = [];

  // Header
  lines.push(`## 🛡️ Secure Code Auditor — Security Analysis Report`);
  lines.push(`**PR #${pr.number}** | \`${pr.repo}\` | Branch: \`${pr.branch}\` → \`${pr.base}\``);
  lines.push(`**Author:** @${pr.author} | **Commit:** \`${pr.sha}\``);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Summary table
  lines.push('### 📊 Summary');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| Overall Risk | ${riskEmoji} **${meta.final_risk_level}** |`);
  lines.push(`| Files Analyzed | ${stats.analyzedFiles} / ${stats.totalFiles} |`);
  lines.push(`| Findings (Confirmed) | ${meta.findings_confirmed} |`);
  lines.push(`| Findings (Rejected as FP) | ${meta.findings_rejected} |`);
  lines.push('');

  if (confirmedFindings.length === 0) {
    lines.push('---');
    lines.push('');
    lines.push('### ✅ No Security Issues Found');
    lines.push('');
    lines.push('The AI auditor reviewed all changed files and found no exploitable vulnerabilities.');
    lines.push('');
  } else {
    lines.push('---');
    lines.push('');

    // Each confirmed finding
    for (const vf of confirmedFindings) {
      const f = vf.finding;
      const sevEmoji = SEVERITY_EMOJI[vf.final_severity] || '⚪';
      const conf = Math.round((vf.validator_confidence || 0) * 100);

      lines.push(`### ${sevEmoji} ${f.id} — ${f.title} [${vf.final_severity}]`);
      lines.push(`> **OWASP:** ${f.owasp_category} | **CWE:** ${f.cwe_id} | **Confidence:** ${conf}%`);
      lines.push(`> **Validator Verdict:** ${VERDICT_EMOJI[vf.verdict] || vf.verdict}`);
      if (vf.original_severity !== vf.final_severity) {
        lines.push(`> ⚠️ *Severity adjusted: ${vf.original_severity} → ${vf.final_severity}*`);
      }
      lines.push('');

      lines.push(`**📍 Location:** \`${f.file}\` | Lines ${f.line_range}`);
      lines.push('');

      if (f.vulnerable_code) {
        lines.push('**🔍 Vulnerable Code:**');
        lines.push('```');
        lines.push(f.vulnerable_code);
        lines.push('```');
        lines.push('');
      }

      lines.push(`**⚠️ Explanation:**`);
      lines.push(f.explanation || '');
      lines.push('');

      if (f.attack_vector) {
        lines.push(`**🎯 Attack Vector:**`);
        lines.push('```');
        lines.push(f.attack_vector);
        lines.push('```');
        lines.push('');
      }

      if (f.remediation) {
        lines.push('**💡 Remediation:**');
        lines.push(f.remediation.description || '');
        if (f.remediation.fixed_code) {
          lines.push('```');
          lines.push(f.remediation.fixed_code);
          lines.push('```');
        }
        lines.push('');
      }

      if (vf.validator_notes) {
        lines.push(`**🔎 Validator Notes:** *${vf.validator_notes}*`);
        lines.push('');
      }

      lines.push('---');
      lines.push('');
    }
  }

  // Clean areas
  if (actorReport.clean_areas?.length > 0) {
    lines.push('### ✅ Clean Areas');
    for (const area of actorReport.clean_areas) {
      lines.push(`- ${area}`);
    }
    lines.push('');
  }

  // Rejected (FP) findings
  if (rejectedFindings.length > 0) {
    lines.push('### 🚫 Rejected Findings (False Positives Filtered)');
    lines.push('');
    lines.push('| ID | Reason |');
    lines.push('|----|--------|');
    for (const vf of rejectedFindings) {
      lines.push(`| ${vf.original_id} | ${vf.validator_notes || 'False positive'} |`);
    }
    lines.push('');
  }

  // Recommendations
  if (actorReport.recommendations?.length > 0) {
    lines.push('### 🔧 General Recommendations');
    lines.push('');
    actorReport.recommendations.forEach((r, i) => lines.push(`${i + 1}. ${r}`));
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push(`*🤖 Generated by [Secure Code Auditor](https://github.com/secure-auditor) v1.0*`);
  lines.push(`*⚠️ This report is auto-generated. Human review required for CRITICAL and HIGH findings.*`);

  return lines.join('\n');
}
